# Exported from Render on 2024-09-23T04:37:55Z
services:
- type: web
  name: PythonLibraryPDFsProject
  runtime: python
  repo: https://github.com/lfvldvn/PythonLibraryPDFsProject
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  region: virginia
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeploy: false
version: "1"
